#include <iostream>
#include <string>
#include <cstdlib>
#include <cctype>
#include <stack>
#include <stdio.h>
#include <array>
#include <math.h>
#include <algorithm>
#include <cstdio>
#include <list>
#include <queue>
#include <map>
#include <set>
#include <vector>
#include <deque>
#include <chrono>
#include <numeric>
#include <random>
#include <iomanip>
#include <functional>
#include <bitset>
#include <complex>
#include <fstream>
#include <sstream>
#include <memory>
#include <tuple>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <future>
#include <atomic>
#include <locale>
#include <stdexcept>
#include <limits>
#include <regex>
#include <valarray>
#include <climits>
#include <cfloat>
#include <cwchar>
#include <cwctype>
#include <csignal>
#include <cerrno>
#include <cstddef>
#include <cassert>
#include <clocale>
#include <typeinfo>
#include <ios>
#include <iosfwd>
#include <istream>
#include <ostream>
#include <fstream>
#include <streambuf>
#include <locale>
#include <codecvt>
#include <scoped_allocator>
#include <initializer_list>
#include <system_error>
#include <exception>
#include <new>
#include <unordered_map>
#include <unordered_set>

using namespace std;

int main() {
    cout << "Hello World";
    return 0;
}
